version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks: 
      - net
    volumes:
      - data:/data/db

  server:
    container_name: fastapi
    build: ./server
    command: python main.py
    networks:
      - net
    restart: always
    env_file:
      - ".env"
    ports:
      - 8000:8000
    depends_on:
      - mongo

networks:
  net:
    driver: bridge
