---
- name: Install Docker and Docker-compose
  hosts: centos
  become: yes
  # run with -K argument(ass-become-pass)
  tasks:
    - name: update packages
      command: yum update -y

    - name: install utilities 
      command: yum install -y yum-utils
      
    - name: add repo
      command: yum-config-manager \
               --add-repo \
               https://download.docker.com/linux/centos/docker-ce.repo

    - name: install docker-engine, docker and docker-compose
      command: yum install docker-ce \ 
               docker-ce-cli containerd.io \
              docker-compose-plugin -y

    - name: enable docker daemon
      command: systemctl enable docker
      command: systemctl start docker
