version: '3.1'

services:
  server:
    container_name: fastapi
    build: ./
    restart: always
    expose:
      - "8000"
    networks:
      - net
    depends_on:
      - mongo
    volumes:
     - ./logs:/debug/

  bot:
    container_name: telegram-bot
    build: aiogrambot/.
    restart: always
    networks:
     - net
    depends_on:
     - server

  mongo:
    container_name: mongo
    image: mongo:5.0
    restart: always
    ports:
     - 27017:27017
    networks: 
      - net
    volumes:
      - ./dbdata:/data/db

  web:
    container_name: vue3
    build: web-app/.
    restart: always
    ports:
      - 80:80
    networks:
      - net
    depends_on:
      - server

networks:
  net:
    driver: bridge
